#cloudbuild.yaml
steps:
  # Build the container image
  - name: "docker/compose:1.26.0"
    args: ["-f", "docker-compose.production.yml", "build", "authserver"]
    env:
      - "DB_NAME=$_DB_NAME"
      - "DB_HOST=$_DB_HOST"
      - "DB_PASS=$_DB_PASS"
      - "DB_USER=$_DB_USER"
      - "DB_PORT=$_DB_PORT"
      - "JWT_SECRET=$_JWT_SECRET"
      - "SESSION_KEY=$_SESSION_KEY"
      - "STATE_HASH_KEY=$_STATE_HASH_KEY"
      - "GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID"
      - "GOOGLE_CLIENT_SECRET=$_GOOGLE_CLIENT_SECRET"
      - "GOOGLE_CLIENT_REDIRECT_URL=$_GOOGLE_CLIENT_REDIRECT_URL"
      - "ADMIN_CLIENT_ID=$_VUE_APP_CLIENT_ID"
      - "ADMIN_CLIENT_SECRET=$_VUE_APP_CLIENT_SECRET"
      - "ADMIN_CLIENT_DOMAIN=$_VUE_APP_REDIRECT_URL"
      - "AUTH_ALLOWED_ORIGIN=$_VUE_APP_REDIRECT_URL"
      - "REDIS_SERVER_HOST=$_REDIS_SERVER_HOST"
      - "REDIS_SERVER_PORT=$_REDIS_SERVER_PORT"
    # Tag auth-server container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "abdulmuhsin/auth-server:latest",
        "gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA",
      ]
  # Push the auth-server container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "authserver"
      - "--image"
      - "gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
images: ["gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA"]
