#cloudbuild.yaml
steps:
  # Build the container image
- name: 'docker/compose:1.26.0'
  args: ['-f', 'docker-compose.production.yml', 'build']
  # Tag admin-client container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'abdulmuhsin/admin-client:latest', 'gcr.io/$PROJECT_ID/admin-client:$COMMIT_SHA']
  # Tag ecormmerce-api container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'abdulmuhsin/ecormmerce-api:latest', 'gcr.io/$PROJECT_ID/ecommerce-api:$COMMIT_SHA']
  # Tag auth-server container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'abdulmuhsin/auth-server:latest', 'gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA']
  # Push the admin-client container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/admin-client:$COMMIT_SHA']
  # Push the ecormmerce-api container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ecommerce-api:$COMMIT_SHA']
# Push the auth-server container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA']
  # Deploy admin-client container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'adminclient'
  - '--image'
  - 'gcr.io/$PROJECT_ID/admin-client:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  # Deploy ecormmerce-api container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'ecormmerceapi'
  - '--image'
  - 'gcr.io/$PROJECT_ID/ecommerce-api:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'authserver'
  - '--image'
  - 'gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
images: ['gcr.io/$PROJECT_ID/admin-client:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/ecommerce-api:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/auth-server:$COMMIT_SHA']
