version: '3'

services:
  ecommerceapi:
    container_name: ecormmerce-api
    image: abdulmuhsin/ecormmerce-api
    hostname: ecormmerce-api
    build:
      context: ./ecormmerce-rest-api
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      PORT: 8080
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_CLIENT_SECRET: ${ADMIN_CLIENT_SECRET}
      ADMIN_CLIENT_DOMAIN: ${ADMIN_CLIENT_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_SERVER_HOST: ${REDIS_SERVER_HOST}
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESOURCE_ALLOWED_ORIGIN: ${RESOURCE_ALLOWED_ORIGIN}
  #  networks:
  #  - ecormmercenet
    ports:
    - 8080:8080
    labels:
      kompose.service.type: LoadBalancer

  authserver:
    container_name: auth-server
    image: abdulmuhsin/auth-server
    hostname: auth-server
    build: 
      context: ./auth-server
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      PORT: 8080 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      SESSION_KEY: ${SESSION_KEY}
      STATE_HASH_KEY: ${STATE_HASH_KEY}
      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_CLIENT_SECRET: ${ADMIN_CLIENT_SECRET}
      ADMIN_CLIENT_DOMAIN: ${ADMIN_CLIENT_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_SERVER_HOST: ${REDIS_SERVER_HOST}
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_REDIRECT_URL: ${GOOGLE_CLIENT_REDIRECT_URL}
      AUTH_ALLOWED_ORIGIN: ${AUTH_ALLOWED_ORIGIN}
  #  networks:
  #  - ecormmercenet
    ports:
    - 8080:8080
    labels:
      kompose.service.type: LoadBalancer

  adminclient:
    container_name: admin-client
    image: abdulmuhsin/admin-client
    hostname: admin-client
    build: 
      context: ./admin-client
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      VUE_APP_ClientID: ${VUE_APP_ClientID}
      VUE_APP_ClientSecret: ${VUE_APP_ClientSecret}
      VUE_APP_Scopes: ${VUE_APP_Scopes}
      VUE_APP_RedirectURL: ${VUE_APP_RedirectURL}
      VUE_APP_AUTH_URL: ${VUE_APP_AUTH_URL}
      VUE_APP_AuthURL: ${VUE_APP_AuthURL}
      VUE_APP_TokenURL: ${VUE_APP_TokenURL}
      VUE_APP_ECOMMERCE_API_URL: ${VUE_APP_ECOMMERCE_API_URL}
  #  networks:
  #  - ecormmercenet
    ports:
    - 8080:8080
    labels:
      kompose.service.type: LoadBalancer

#networks:
#  ecormmercenet:
#    driver: bridge