version: '3'

services:
  ecormmercedb:
    container_name: ecormmercedb
    image: postgres
    environment:
      GET_HOST_FROM: dns
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    hostname: ecormmercedb
    ports:
      - 5434:5434
    volumes:
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/1-init_db.sql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/2-schema.sql
    networks:
      - ecormmercenet

  ecommerceapi:
    container_name: ecormmerce-api
    image: abdulmuhsin/ecormmerce_app:v1
    hostname: ecormmerce-api
    env_file: .env
    build:
      context: ./ecormmerce-rest-api
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST_DOCKER}
      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_CLIENT_SECRET: ${ADMIN_CLIENT_SECRET}
      ADMIN_CLIENT_DOMAIN: ${ADMIN_CLIENT_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_SERVER_HOST: ${REDIS_SERVER_HOST}
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT_DOCKER}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      RESOURCE_ALLOWED_ORIGIN: ${RESOURCE_ALLOWED_ORIGIN}
    networks:
    - ecormmercenet
    volumes:
    - .:/go/src/ecormmerce-app/ecormmerce-rest-api
    ports:
    - 8081:8081
    depends_on:
    - ecormmercedb
    - redisdb
    links:
    - ecormmercedb
    - redisdb
    labels:
      kompose.service.type: LoadBalancer

  authserver:
    container_name: auth-server
    image: abdulmuhsin/auth-server:v1
    hostname: auth-server
    env_file: .env
    build: 
      context: ./auth-server
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST_DOCKER}
      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_CLIENT_SECRET: ${ADMIN_CLIENT_SECRET}
      ADMIN_CLIENT_DOMAIN: ${ADMIN_CLIENT_DOMAIN}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_SERVER_HOST: ${REDIS_SERVER_HOST}
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT_DOCKER}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      AUTH_ALLOWED_ORIGIN: ${AUTH_ALLOWED_ORIGIN}
    networks:
    - ecormmercenet
    volumes:
    - .:/go/src/ecormmerce-app/ecormmerce-rest-api/auth-server
    ports:
    - 9096:9096
    depends_on:
    - ecormmercedb
    - redisdb
    links:
    - ecormmercedb
    - redisdb
    labels:
      kompose.service.type: LoadBalancer

  adminclient:
    container_name: admin-client
    image: abdulmuhsin/admin-client:v1
    hostname: admin-client
    env_file: admin-client/.env
    build: 
      context: ./admin-client
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
    - ecormmercenet
    volumes:
    - .:/go/src/ecormmerce-app/ecormmerce-rest-api/admin-client
    ports:
    - 8080:80
  
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_SERVER_PASS}
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
    - ecormmercenet

networks:
  ecormmercenet:
    driver: bridge